# config.yaml

targets:
  - 192.168.0.0/24

ports: "1-65535"

output_dir: "./logs"

alert_rules:
  - port: 23
    severity: high
  - port: 3389
    severity: medium


scan_options:
  aggressive: false
  service_version: false
  skip_host_directory: true
alerts:
  risky_ports: [21, 23, 3389]
  risky_services:
    - ftp
    - telnet
    - rdp