# config.yaml

targets:
  - 192.168.0.0/24

ports: "1-65535"

output_dir: "./logs"

alert_rules:
  - port: 23
    severity: high
  - port: 3389
    severity: medium


scan_options:
  aggressive: false
  service_version: true
  skip_host_directory: false
alerts:
  risky_ports: [21, 23, 25, 110, 135, 139, 445, 1433, 3306, 3389, 5900, 8080]
  risky_services:
    - ftp
    - telnet
    - smtp
    - POP3
    - MSRPC
    - NetBIOS
    - SMB
    - MSSQL
    - MySQL
    - RDP
    - VNC
    - HTTP Alt